### ISSUE TITLE
WordPress Creator Connections: Connecting Influencers to Affiliate Programs

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/marketing#357]
### Comment

Over several years, numerous folks have noted the challenge presented by WordPress competitors paying influencers and creators to promote their products. A few months ago, @jonoalderson [pointed to a specific case of Wix buying favorable opinions](https://wordpress.slack.com/archives/C0GKJ7TFA/p1677760310729459).

More recently, a popular creator on YouTube (unnamed to protect their business) noted that he’s successfully using WordPress to run his business and processing thousands of orders annually. Despite this, he ends the video with an ad spot for Squarespace. The software keeping his business running gets a 5-second mention, while Squarespace gets a dedicated minute-long spot.

Affiliate partnership opportunities exist within the WordPress ecosystem but can be hard to find. A new _“WordPress Creator Connections”_ (working title) landing page on WordPress.org could help connect creators to these existing programs. This way, they can share their love of WordPress, make money, and stop pushing their audiences to our competitors.

## Project Scope

As a proof of concept, we can start with the hosts listed on the [hosting](https://href.li/?https://wordpress.org/hosting/) page, as they each already offer an affiliate program. These companies are also already involved in the broader community, and using this list should allow us to implement an MVP quickly. Later iterations of this page could include additional companies and resources such as promotional materials, orchestrated campaigns, and more. The goal of this initial phase is to establish a new page quickly and then review data to determine the level of demand and engagement with these opportunities.

## Success Metrics

Primary success metric: Page visits (I.e. Are online creators finding this content?)
Other metrics: Page clicks, New WordPress installs, Successful referrals

## Tasks

- [x] Draft landing page copy (working doc: [WordPress Creator Connections](https://docs.google.com/document/d/16vgEbZZvwgRcgxbwIJAy9BxCjLs7nWz8SQm3z-mi75c/edit))
- [x] Share copy draft with Design Team and [#website-redesign](https://wordpress.slack.com/archives/C04U953K77A) group
- [x] https://github.com/WordPress/wporg-main-2022/issues/433
- [x] 30-day measurement period
- [ ] Add Hostinger (new addition to /hosting page)
- [x] Amplify new page across social platforms
- [ ] 90-day measurement period
- [ ] 6-month measurement period

**Comment by eidolonnight** [comment]
@rmartinezduque and I started drafting a bit of copy for this page based on the idea that we could re-use the template for /hosting and keep the design simple for this MVP. This is only a few hours work, so we welcome feedback.

**Comment by Bretteroo** [comment]
Brett from DreamHost here.  We think this is a great idea and would be happy to be featured in whatever form makes sense.  We'd be happy to provide text for the page, graphics, a landing page on our side...whatever you'd need to make this initiative successful.

**Comment by StacyCarlson01** [comment]
I think this is a beautiful idea!! I've been chatting with the other products at WordCamp, and I think it would be awesome to bring more light to the affiliate programs they have going.

**Comment by thetinyl** [comment]
👋 I've finally had a chance to come back to this landing page. I think it's mostly ready to go, my only question is whether or not the hosts sections would be stronger with language that was focused on the affiliate programs vs. hosting services. 

I've made some [suggestions in the copy draft](https://docs.google.com/document/d/16vgEbZZvwgRcgxbwIJAy9BxCjLs7nWz8SQm3z-mi75c/edit?disco=AAABSP0QQEI) to illustrate what I mean. I think keeping the copy there short and relevant to the goals of the page (sharing affiliate opportunities for online creators) is a stronger direction. I'd love to know your thoughts @Bretteroo and @StacyCarlson01, and also make sure we're speaking to some of the values of each program appropriately. 

I'm also curious about any concerns or risks that come up for you. Some that come to mind are: 
- Keeping the content current if affiliate programs change—is there a low-effort way to manage that? Do programs tend to change often? 
- Talking about specific money/compensation in an open source context—does this feel inappropriate for WordPress.org?

In the meantime, I've built the page in the Editor with the current content. Progress on that can be followed at [this GitHub issue](https://github.com/WordPress/wporg-main-2022/issues/433) in the WP.org repo. Any subsequent changes/iterations we want to make on content are easy to do even after the page is live.

**Comment by Bretteroo** [comment]
Thanks for working on this, @thetinyl!  Looking great so far.

* I've updated the text for DreamHost in the copy to put the focus more on the affiliate program itself and less on our  brand.  I agree - that's where the focus should be.
* Our affiliate program terms/platform/linking info change very, very infrequently.  On the order of once every several years.
* Having specific dollar amounts on the page definitely feels like more of a wp community decision.  I don't personally see it as being out-of-place any more than the affiliate page itself might be.  If it helps, we are comfortable with having our payout prices appear on the page.

**Comment by thetinyl** [comment]
Thanks @Bretteroo! 

> I've updated the text for DreamHost in the copy to put the focus more on the affiliate program itself and less on our brand. 

I've made a suggestion for how to condense the text you provided. It's still a bit long for the layout we're working with. Let me know if you have a preferred edit or if the suggestion works for you. 

I also appreciate the additional thoughst/context. I figured affiliate programs might not change so much, but you never know.

**Comment by eidolonnight** [comment]
## Metrics since launch

- Page visits: 72
- Program clicks: 10

## Next steps

- I’ve drafted and scheduled social campaign content with help from @rmartinezduque and @bjmcsherry. Content will start going out next week after WCUS.
- I intend to do some hands-on outreach to WordPress users currently promoting competitors. I welcome anyone else who wants to do this as well. Questions to ask:
  - I see that you’re using WordPress but promoting [competitor]. Is this due to your sponsorship or other reasons?
  - Are you able to discuss your partnership with [competitor]?
  - Are you aware of the ways in which you can earn by promoting WordPress?
  - What would change your mind about promoting WordPress in the future?
- I've updated the page excerpt (what displays in search and social) to quickly highlight what the page contains.

**Comment by mdemop** [comment]
> As of August 9th, the [Creator Connections page](https://wordpress.org/creator-connections/) is live.

This page looks great! I am curious on how other WordPress companies with Affiliate programs get added? What is the process, vetting and associated costs? I think this could also be a source of revenue for the Foundation or PBC. 

I know that [Affiliate Hunter](https://www.bestaffiliateprograms.io) has a curated list of many programs, many of which are WP related and we (Codeable) would love to be listed as well.

**Comment by eidolonnight** [comment]
> I am curious on how other WordPress companies with Affiliate programs get added? What is the process, vetting and associated costs?

For this first iteration, the companies highlighted are those that have been vetted and approved by Matt for listing on the [WordPress.org/hosting/](https://wordpress.org/hosting/) page.

This approach was specifically taken to avoid needing to create a whole new set of criteria and processes, and then selecting the right people to curate the list. IFF this initiative proves successful (i.e. we observe a growing number of page visits and clicks) then I think it would make sense to explore expanding the offering.

> I think this could also be a source of revenue for the Foundation or PBC.

For now, the goal is to see if this attracts the attention of creators and meets their needs. Eventually growing this into a revenue source would be nice, but there will likely be organizational, technical, and possibly legal hurdles for that (i.e. out of scope).

> we (Codeable) would love to be listed as well.

If _anyone_ wants to reach out to creators and report back here, that help would be appreciated. If I were running an affiliate program at a WordPress-based company, I'd certainly be contacting any creator currently pushing competitor products and inquiring how to get them to switch. There's no need to wait to be listed here.

**Comment by eidolonnight** [comment]
This project was delayed and is now stale. Any future attempt should not be based solely on /hosting and will require new stakeholders.
